(TeX-add-style-hook
 "Chapter2"
 (lambda ()
   (LaTeX-add-labels
    "chap2"
    "C2-sec:model"
    "C2-Sketch"
    "C2-sec:Governing equation"
    "C2_V1"
    "C2-Npressure"
    "C2-pression"
    "C2-vel"
    "C2-Q0"
    "C2-eq12"
    "C2-eq11"
    "C2-Mass"
    "C2-Heq"
    "C2-sec:dimens-equat"
    "L1"
    "H1"
    "T1"
    "C2-sec:need-regularization"
    "C2-sec:regime-propagations"
    "C2-sec:bending-regime"
    "C2-sec:grav-curr-regime"
    "IntrusionShape"
    "WaveVelocity"
    "ScalingR"
    "ScalingH"
    "Lp"
    "Scaling-R-Gravi"
    "Scaling-H-Gravi"
    "C2-sec:appl-earth-moon"
    "C2-sec:discussion"
    "tab2"
    "tab3")))

