(TeX-add-style-hook
 "Chapter2"
 (lambda ()
   (LaTeX-add-labels
    "chap2"
    "sec:model-1"
    "sec:formulation-1"
    "C2-Sketch"
    "sec:Velocity field"
    "C2_V1"
    "C2-Npressure"
    "C2-V2"
    "C2-Q0"
    "C2-eq12"
    "C2-eq11"
    "chap2-sec:governing-equations"
    "C2-Mass"
    "C2-EqConservation"
    "C2-Heq"
    "sec:dimens-equat-1"
    "L1"
    "H1"
    "T1"
    "tab2"
    "tab3"
    "sec:regime-propagations"
    "sec:bending-regime"
    "sec:grav-curr-regime"
    "IntrusionShape"
    "WaveVelocity"
    "ScalingR"
    "ScalingH"
    "Lp"
    "Scaling-R-Gravi"
    "Scaling-H-Gravi"
    "sec:appl-earth-moon"
    "sec:discussion")))

