(TeX-add-style-hook
 "Chapter5"
 (lambda ()
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "url")
   (LaTeX-add-labels
    "C5-chap6"
    "C5-Introduction"
    "C5-FFC"
    "C5-fig5-1"
    "C5-tab1"
    "C5-Crater_Topography"
    "C5-fig3-1"
    "C5-3-3"
    "C5-topo"
    "C5-3-2"
    "C5-topo1"
    "C5-fig3-2"
    "C5-Equation_Momentum"
    "C5-eq4"
    "C5-eq5"
    "C5-eq6"
    "C5-eq8"
    "C5-eq8a"
    "C5-eq10"
    "C5-Injection_Rate"
    "C5-eq12"
    "C5-eq11"
    "C5-Final_Equation"
    "C5-eq15"
    "C5-eq16"
    "C5-Dimensionless_Equation"
    "C5-eq18"
    "C5-eq19"
    "C5-eq99"
    "C5-eq20"
    "C5-eq21"
    "C5-eqqqq"
    "C5-Dimensionless1"
    "C5-n1"
    "C5-n2"
    "C5-n3"
    "C5-n4"
    "C5-n5"
    "C5-TopoFinal"
    "C5-Dimensionless_Number"
    "C5-tab2"
    "C5-tab3"
    "C5-Strengthless_Layer1"
    "C5-eq22"
    "C5-fig4-2"
    "C5-Constant_Thickness"
    "C5-fig4-1"
    "C5-eq5.1"
    "C5-eq4-1"
    "C5-fig4-3"
    "C5-fig4-4"
    "C5-fig4-5"
    "C5-SimpleCrater"
    "C5-fig4-6"
    "C5-5.3"
    "C5-eq5.4"
    "C5-eq5.4.5"
    "C5-fig4-7"
    "C5-DepthIntrusion"
    "C5-eq5-2"
    "C5-InjectionRateDiscussion"
    "C5-diff"
    "C5-eq5-3")))

